# Generated by Django 5.2.8 on 2026-02-15 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_delete_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teach',
            name='category',
            field=models.CharField(choices=[('chemistry', 'شیمی'), ('graphic', 'گرافیک'), ('sport', 'تربیت بدنی'), ('programming', 'برنامه نویسی'), ('programming', 'زبان انگلیسی')], max_length=20),
        ),
        migrations.AlterField(
            model_name='teach',
            name='educational_stage',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='teach',
            name='field_of_study',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='teach',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='teach',
            name='university',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
