# Generated by Django 5.2.8 on 2025-12-07 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_futurecurse'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='futurecurse',
            new_name='futurecourses',
        ),
    ]
