# Generated by Django 5.2.8 on 2025-12-08 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_article_bestteachers'),
    ]

    operations = [
        migrations.AddField(
            model_name='bestteachers',
            name='image',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
