# Generated by Django 5.2.8 on 2026-02-22 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_teach_title'),
    ]

    operations = [
        migrations.DeleteModel(
            name='new_login',
        ),
    ]
