# Generated by Django 5.2.8 on 2025-12-15 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_article_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('ongoing', 'در حال برگزاری'), ('completed', 'تکمیل شده'), ('upcoming', 'در انتظار شروع')], default='ongoing', max_length=20, verbose_name='وضعیت دوره'),
        ),
    ]
