# Generated by Django 5.2.8 on 2025-12-15 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_product_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='level',
            field=models.CharField(blank=True, choices=[('مبتدی', 'مبتدی'), ('متوسط', 'متوسط'), ('پیشرفته', 'پیشرفته')], max_length=20, null=True, verbose_name='سطح دوره'),
        ),
    ]
