# Generated by Django 5.2.8 on 2025-12-15 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_alter_product_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='level',
            field=models.CharField(blank=True, choices=[('beginner', 'مبتدی'), ('intermediate', 'متوسط'), ('advanced', 'پیشرفته')], max_length=20, null=True, verbose_name='سطح دوره'),
        ),
    ]
