# Generated by Django 5.2.8 on 2025-12-17 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_teach'),
    ]

    operations = [
        migrations.AddField(
            model_name='teach',
            name='comment',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
