# Generated by Django 5.2.8 on 2025-12-17 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_teach_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='teach',
            name='category',
            field=models.CharField(choices=[('chemistry', 'شیمی'), ('graphic', 'گرافیک'), ('sport', 'تربیت بدنی'), ('programming', 'برنامه نویسی')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
