# Generated by Django 5.2.8 on 2025-12-19 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0017_teach_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='futurecoursess',
            name='teacher',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
