# Generated by Django 5.2.8 on 2025-12-29 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0019_test_teacher_test_info_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('teach', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.test_teacher')),
            ],
        ),
    ]
