# Generated by Django 5.2.8 on 2025-12-29 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0021_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='teach',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='product.teach'),
            preserve_default=False,
        ),
    ]
