# Generated by Django 5.2.8 on 2025-12-29 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0022_product_teach'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sessions',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
