# Generated by Django 5.2.8 on 2025-12-29 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0023_product_sessions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teach',
            old_name='course_title',
            new_name='educational_stage',
        ),
    ]
