# Generated by Django 5.2.8 on 2025-12-29 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0024_rename_course_title_teach_educational_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='teach',
            name='field_of_study',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teach',
            name='image',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teach',
            name='university',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
