# Generated by Django 5.2.8 on 2025-12-29 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0025_teach_field_of_study_teach_image_teach_university'),
    ]

    operations = [
        migrations.AddField(
            model_name='teach',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True),
        ),
    ]
