# Generated by Django 5.2.8 on 2025-12-29 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0026_teach_slug'),
    ]

    operations = [
        migrations.DeleteModel(
            name='courses',
        ),
    ]
