# Generated by Django 5.2.8 on 2026-01-05 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0027_delete_courses'),
    ]

    operations = [
        migrations.RenameField(
            model_name='test_teacher',
            old_name='lname',
            new_name='lastname',
        ),
    ]
